version: '3.8'

services:
    backend:
        build: 'backend/'
        ports:
            - '${BACK_PORT}:${BACK_PORT}'
        networks:
            - backend
        restart: unless-stopped

    discord-bot:
        build: 'backend_discord_service/'
        ports:
            - '${DISCORD_BOT_PORT}:${DISCORD_BOT_PORT}'
        networks:
            - backend_discord_service
        restart: unless-stopped

    web:
        build: 'web/'
        ports:
            - '${FRONT_PORT}:${FRONT_PORT}'
        depends_on:
            - mobile
        networks:
            - web/
        restart: unless-stopped

    mobile:
        build: 'mobile/'
        networks:
            - mobile
        restart: unless-stopped
