version: '3.8'

services:
    backend:
        build: 'backend/'
        ports:
            - '${BACK_PORT}:3000'
        networks:
            - backend

    backend_discord_service:
        build: 'backend_discord_service/'
        ports:
            - '${DISCORD_BOT_PORT}:3000'
        depends_on:
            - backend
        networks:
            - backend_discord_service

    web:
        build: 'web/'
        ports:
            - '${FRONT_PORT}:3000'
        depends_on:
            - backend
            - mobile
        volumes:
            - apk:/mobile/

    mobile:
        build: 'mobile/'
        volumes:
            - apk:/mobile/


networks:
    backend:
    backend_discord_service:
volumes:
    apk:
