export const CLIENT_ID_GITHUB_CREATE_AREA = "CLIENT_ID_GITHUB_CREATE_AREA_KEY";
export const CLIENT_ID_GITHUB_LOGIN = "CLIENT_ID_GITHUB_LOGIN_KEY";
export const CLIENT_ID_GOOGLE_CREATE_AREA = "CLIENT_ID_GOOGLE_CREATE_AREA_KEY";
export const CLIENT_ID_SPOTIFY_CREATE_AREA = "CLIENT_ID_SPOTIFY_CREATE_AREA_KEY";