name: Main workflow

on: [ push ]

env:
  MIRROR_URL: "git@github.com:EpitechPromo2026/B-DEV-500-PAR-5-1-area-leo.l-huillier.git"

jobs:
  build:
    name: Check compilation
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
      - name: Build web
        run: cd web/ && npm install && npm run build
      - name: Build server
        run: cd server/ && npm install && npm run build

  test:
    name: Run tests
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3

  push_to_mirror:
    name: Push to Epitech repository
    runs-on: ubuntu-latest
    if: ${{ github.event_name }} == "push"
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cloning to mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}

    needs:
        - build